### ISSUE TITLE
Questions about the solver

### ISSUE THREAD

**Issue by swoyer2** [ItsAsShrimpleAsThat/FillerSolver#1]
Hi! I am working on a similar project for a youtube video and have been running into the problem of my search slowing down an insane amount after a depth >16. I was looking up if anyone else had this idea for a project and found yours. However when I try to use the solver you made it is either really slow or not working (I think the second since I tried depth of 8). Is it working for you and I just don't understand how to use it, or are you still developing it? Also if it does work for you how long is it taking you to solve a game/how deep do you have to go? I am thinking it takes around 20 moves to solve a game but that is just an estimate since I have not been able to test it.

Thank you!

**Comment by swoyer2** [comment]
Also I have been using python instead of JS, which could be causing it to be a lot slower. However I am not a great programmer so I would not be surprised if I am overlooking some speed increases from algorithms. When your engine runs does it use alpha beta pruning to realize when all branches have the same starting move, then cutting the search off early and outputting that move? I was thinking this could be a speed increase but I was not sure how to implement that as my alpha beta pruning checks each color first, (It does all children of green, all children of black... etc.). Any tips as to how you sped your alg up would be helpful :)

**Comment by ItsAsShrimpleAsThat** [comment]
Hi swyower2!
   I am currently on vacation, but I will be back in a few days and I can look at your code then. For now, the most likely reason that the solver is not working is the fact that iterative deepening is currently not implemented, so if you have that box checked, the solver won't do anything. Try unchecking that to use the solver. 
    Until then, I wish the best for you! Once you finish I will definitely look at your video!
Thanks,
    me i guess idk what to sign off with lmao

**Comment by swoyer2** [comment]
Hi!

I hope you are having a good vacation. This is by no means important so if you do not want to help don't worry about it lol. I got your solver to work and it is very fast compared to mine. So I am curious as to the differences between mine and yours. I have tried reading the JS but I have never programmed in JS and really only have experience in Python for personal projects. I get some of it but I feel like if you wanted to chat sometime about it I could better understand.

Thank you so much!
:)

**Comment by swoyer2** [comment]
Also I have questions about the Quiescence search, why is it >3 or >0.5*territory? Aren't there moves that capture more than 3 that would be worse than playing a move that captures 2 colors? The case of 3 pieces being blocked off by the player (like a wall). Those pieces are already part of the players score no matter what, so spending a turn capturing them early just makes the player behind a turn. Unless I am misunderstanding which is very likely. 

Thank you,
Swoyer2

**Comment by ItsAsShrimpleAsThat** [comment]
Hi!
I just saw your video on your AI. I was going to make a video once I finished fine, but since yours exists, I probably won't lmao. I'm a very big fan of it!

To answer your question about the quiescence search, I believe you are misunderstanding the quiescence search.
![diagram](https://i.imgur.com/hvDcbGh.png)
Here's a little diagram that I hope got uploaded correctly.
The quiescence search happens **after** the regular search is done on every position that is not considered quiet. The idea behind this is that it helps achieve a position that is stable, where the position will not drastically change in one move. I'll use an example from chess. Let's say we are searching to a depth of 20 and on the 20th move, we captured a pawn with our queen. Great! Since we won a pawn, this position was the best we found for ourselves at depth 20, so we play the move that will take us down this path. What we didn't realize is that on move 21, the opponent can just capture our queen. The idea of the quiescence search is to prevent this kind of situation. We guarantee that the final position we reach is safe to end our search on.

I would love to see the source code of your version, considering that it takes 3 hours to search to a depth of 18. I'll see if I can find any optimizations for you!
Thanks,
Avi

**Comment by swoyer2** [comment]
Hi!

I understand that now! That is a good explanation, thank you very much. You could probably still make a video on the same topic and it will do well, I am sure you are more knowledgeable on the details. I will make my code available probably within the next 1-3 days, it will just be on this github. Also how did you find the video? Was it just recommended or did you search for it? I was surprised to see your comment lol.

Thank you :)

**Comment by swoyer2** [comment]
Fuck it I made it public lmao. I added a little bit of comments and a readme. It is not great code as I did not expect anyone to see it, also the readme is basic but should explain how to use the program (especially if you have experience with coding which you do). :)

**Comment by ItsAsShrimpleAsThat** [comment]
I just got the video in my recommended lol. I assumed it was some other person's filler AI, as I'm pretty sure others exist out there, so I was quite surprised to see my AI in the video.

Now that the code is public I'll take a quick look at it haha
